---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: source-code
  - name: version

outputs:
  - name: build-artifact-output
    path: build/libs

run:
  path: source-code/ci/tasks/build-artifact.sh
