---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: source-code

outputs:
  - name: jar-file
    path: build/libs

run:
  path: source-code/ci/build.sh
