---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
  - name: source-code

run:
  path: "source-code/gradlew"
  args: ["--no-daemon", "build"]
