resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/wooz86/musiclookup.git
      branch: master

  - name: docker-image
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/musiclookup

jobs:
  - name: build
    plan:
      - get: source-code
        trigger: true
      - task: gradle-build
        file: source-code/ci/gradle-build.yml
      - task: prepare-docker-build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          inputs:
            - name: source-code
            - name: jar-file
          outputs:
            - name: docker-files
              path: jar-file
          run:
            path: cp source-code/Dockerfile jar-file/
      - put: docker-image
        params:
          build: docker-files
