resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/wooz86/musiclookup.git

jobs:
  - name: build
    public: true
    plan:
      - get: source-code
        trigger: true
      - task: gradle-build
        file: source-code/ci/build.yml
