resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/wooz86/musiclookup.git
      branch: master


jobs:
  - name: unit
    plan:
    - get: source-code
      trigger: true
    - task: unit
      file: source-code/ci/tasks/unit.yml
