resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/wooz86/musiclookup.git
      branch: master

  - name: docker-image
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/musiclookup

jobs:
  - name: build
    plan:
      - get: source-code
        trigger: true
      - task: gradle-build
        file: source-code/ci/gradle-build.yml
      - task: prepare-docker-build
        config:
          inputs:
            - name: jar-file
          outputs:
            - name: docker-files
          run:
            path: cp jar-file/* docker-files/*
      - put: docker-image
        params:
          build: docker-files
